parameters:
    # The default_attributes to be used as MetaAttribute objects for MetaProperties.
    # With the 'entity_generator.attributes' config, these attributes can be extended and/or partially overridden:
    # The names and types cannot be altered. Also, meta_properties can be added, but not removed.
    default_attributes:
        name:
            type: 'string'
            meta_properties: ['K3ssen\EntityGeneratorBundle\MetaData\Property\MetaPropertyInterface']
        id:
            type: 'bool'
            meta_properties: ['K3ssen\EntityGeneratorBundle\MetaData\Property\PrimitiveMetaPropertyInterface']
            default: false
        unique:
            type: 'bool'
            meta_properties: ['K3ssen\EntityGeneratorBundle\MetaData\Property\PrimitiveMetaPropertyInterface']
            default: false
        nullable:
            type: 'bool'
            meta_properties: ['K3ssen\EntityGeneratorBundle\MetaData\Property\MetaPropertyInterface']
            default: false
        length:
            type: 'int'
            meta_properties: ['K3ssen\EntityGeneratorBundle\MetaData\Property\HasLengthInterface']
        precision:
            type: 'int'
            meta_properties: ['K3ssen\EntityGeneratorBundle\MetaData\Property\DecimalMetaPropertyInterface']
        scale:
            type: 'int'
            meta_properties: ['K3ssen\EntityGeneratorBundle\MetaData\Property\DecimalMetaPropertyInterface']
        targetEntity:
            type: 'object'
            meta_properties: ['K3ssen\EntityGeneratorBundle\MetaData\Property\RelationMetaPropertyInterface']
        referencedColumnName:
            type: 'string'
            meta_properties: ['K3ssen\EntityGeneratorBundle\MetaData\Property\RelationMetaPropertyInterface']
            default: 'id'
        orphanRemoval:
            type: 'bool'
            meta_properties:
                - 'K3ssen\EntityGeneratorBundle\MetaData\Property\ManyToManyMetaPropertyInterface'
                - 'K3ssen\EntityGeneratorBundle\MetaData\Property\OneToManyMetaPropertyInterface'
            default: false
        inversedBy:
            type: 'string'
            meta_properties:
                - 'K3ssen\EntityGeneratorBundle\MetaData\Property\ManyToOneMetaPropertyInterface'
                - 'K3ssen\EntityGeneratorBundle\MetaData\Property\OneToOneMetaPropertyInterface'
                - 'K3ssen\EntityGeneratorBundle\MetaData\Property\ManyToManyMetaPropertyInterface'
        mappedBy:
            type: 'string'
            meta_properties:
                - 'K3ssen\EntityGeneratorBundle\MetaData\Property\OneToManyMetaPropertyInterface'
                - 'K3ssen\EntityGeneratorBundle\MetaData\Property\OneToOneMetaPropertyInterface'
                - 'K3ssen\EntityGeneratorBundle\MetaData\Property\ManyToManyMetaPropertyInterface'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $attributes: '%entity_generator.attributes%'
            $entityQuestions: !tagged entity_generator.entity_question
            $propertyQuestions: !tagged entity_generator.property_question
            $attributeQuestions: !tagged entity_generator.attribute_question
            $overrideSkeletonPath: '%entity_generator.override_skeleton_path%'
            $autoGenerateRepository: '%entity_generator.auto_generate_repository%'
            $bundlesMetaData: '%kernel.bundles_metadata%'

    K3ssen\EntityGeneratorBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'